# Generated by Django 4.0.2 on 2022-02-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=100, null=True, verbose_name='Cantidad')),
                ('crecedora', models.CharField(max_length=100, null=True, verbose_name='Crecedora')),
                ('engordadora', models.CharField(max_length=100, null=True, verbose_name='Engordadora')),
                ('inversion', models.CharField(max_length=100, null=True, verbose_name='Inversion')),
                ('image', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('descripcion', models.TextField(max_length=100, null=True, verbose_name='Descripcion')),
                ('total', models.CharField(max_length=100, null=True, verbose_name='Total')),
            ],
        ),
    ]
