# Generated by Django 4.0.2 on 2022-02-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='image',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Image'),
        ),
    ]
